name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "[default]" > aws-credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> aws-credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> aws-credentials
          mkdir ~/.aws
          mv aws-credentials ~/.aws/credentials

      - name: Deploy to AWS S3
        run: |
          aws s3 sync ./static-website s3://your-s3-bucket-name --delete

      - name: Invalidate CloudFront cache (optional)
        run: |
          aws cloudfront create-invalidation --distribution-id your-cloudfront-distribution-id --paths "/*"

