name: Upgrade python CI

on:
  workflow_dispatch:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: 5.0
  VERSION2: 7.0

jobs:
  directory:
    runs-on: ubuntu-latest
   
    steps:
    - name: verify the directory
      run: |
        pwd
        ls -lstr
        whoami

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.11, 3.10, 3.9, 3.8, 3.7, 3.6, 3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Check python version
      run: |
        python --version
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    - name: run any python code
      run: |
        ls -ltr
        echo "running datatype_casting"
        python datatype_casting.py
        echo "running basic_calculations"
        python basic_calculations.py
        echo "running dictionary_py"
        python myDict_tough.py
        echo "running os-module function"
        python os-module.py

  compare_versions:
    runs-on: ubuntu-latest

    steps:
    - name: compare both the versions mentioned as envrionmental variables above
      run: |
        pwd
        versioncompare.sh
