name: Upgrade python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Check python version
      run: |
        python --version
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    - name: run any python code
      run: |
        python datatype_casting.py
