name: Upgrade python CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Check python version
      run: |
        python --version
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    - name: run any python code
      run: |
        ls -ltr
        echo "running datatype_casting"
        python datatype_casting.py
        echo "running basic_calculations"
        python basic_calculations.py
        echo "running dictionary_py"
        python myDict_tough.py
        echo "running os-module function"
        python os-module.py


