name: Testing workflow/pipeline with some python-upgrades & basic shell

on:
  workflow_dispatch:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: 5
  VERSION2: 7

#stage1
jobs:
  directory:
    runs-on: ubuntu-latest
    steps:
    - name: verify the directory
      run: |
        pwd
        ls -lstr
        whoami

  #stage2
  build:
    needs: directory
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.10]
    steps:
    - uses: actions/checkout@v4
    - name: Check python version
      run: |
        python --version
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    - name: run any python code
      run: |
        ls -ltr
        echo "running datatype_casting"
        python datatype_casting.py >> artifact.txt
    - name: Uploading artifacts
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: artifact.txt
        if-no-files-found: error
        
  #stage3
  compare_versions:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: compare both the versions mentioned as envrionmental variables above
      run: |
        cat artifacts.txt
        chmod +x versioncompare.sh
        ./versioncompare.sh

